pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=2"
      - check-success=Validation
      - check-success=Format
      - check-success=Lint Check
      - check-success=Xline Operator Test
      - check-success=Commit Message Validation
      - check-success=Spell Check
      - check-success=Configuration changed
      - check-success=DCO
      - check-success=Summary
      - status-success="codecov/patch"
      - status-success="codecov/project"
    actions:
      merge:
        method: rebase
