//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/apps/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XlineCluster) DeepCopyInto(out *XlineCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	if in.objKey != nil {
		in, out := &in.objKey, &out.objKey
		*out = new(types.NamespacedName)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XlineCluster.
func (in *XlineCluster) DeepCopy() *XlineCluster {
	if in == nil {
		return nil
	}
	out := new(XlineCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XlineCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XlineClusterList) DeepCopyInto(out *XlineClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XlineCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XlineClusterList.
func (in *XlineClusterList) DeepCopy() *XlineClusterList {
	if in == nil {
		return nil
	}
	out := new(XlineClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XlineClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XlineClusterRecStatus) DeepCopyInto(out *XlineClusterRecStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XlineClusterRecStatus.
func (in *XlineClusterRecStatus) DeepCopy() *XlineClusterRecStatus {
	if in == nil {
		return nil
	}
	out := new(XlineClusterRecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XlineClusterSpec) DeepCopyInto(out *XlineClusterSpec) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XlineClusterSpec.
func (in *XlineClusterSpec) DeepCopy() *XlineClusterSpec {
	if in == nil {
		return nil
	}
	out := new(XlineClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XlineClusterStatus) DeepCopyInto(out *XlineClusterStatus) {
	*out = *in
	if in.LastApplySpecHash != nil {
		in, out := &in.LastApplySpecHash, &out.LastApplySpecHash
		*out = new(string)
		**out = **in
	}
	out.XlineClusterRecStatus = in.XlineClusterRecStatus
	in.XlineClusterSyncStatus.DeepCopyInto(&out.XlineClusterSyncStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XlineClusterStatus.
func (in *XlineClusterStatus) DeepCopy() *XlineClusterStatus {
	if in == nil {
		return nil
	}
	out := new(XlineClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XlineClusterSyncStatus) DeepCopyInto(out *XlineClusterSyncStatus) {
	*out = *in
	out.StatefulSetRef = in.StatefulSetRef
	out.ServiceRef = in.ServiceRef
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.StatefulSetCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XlineClusterSyncStatus.
func (in *XlineClusterSyncStatus) DeepCopy() *XlineClusterSyncStatus {
	if in == nil {
		return nil
	}
	out := new(XlineClusterSyncStatus)
	in.DeepCopyInto(out)
	return out
}
