apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  storageClassName: xline-backup
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp"
---
apiVersion: xlineoperator.datenlord.io/v1
kind: XlineCluster
metadata:
  name: my-xline-cluster
spec:
  size: 3
  backup:
    cron: "*/15 * * * *"
    pvc:
      metadata:
        name: backup-pvc
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: xline-backup
        resources:
          requests:
            storage: 1Gi
  container:
    image: "datenlord/xline"
    name: "my-xline"
    command:
      - tail
      - -F
      - block_for_sidecar
    ports:
      - containerPort: 2379
        name: grpc
