name: release

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_ID: ghcr.io/xline-kv/xline-operator

jobs:
  build:
    name: Upload Release Asset
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Generate App Version
        id: generate_app_version
        run: echo app_version=`git describe --tags --always` >> $GITHUB_OUTPUT
      - name: Build xline operator image
        run: |
          make docker-build IMG=${{ env.IMAGE_ID }}:${{ steps.generate_app_version.outputs.app_version }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: xline-kv
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image to GHCR
        run: |
          make docker-push IMG=${{ env.IMAGE_ID }}:${{ steps.generate_app_version.outputs.app_version }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
